### ISSUE TITLE
can't open the compressed file

### ISSUE THREAD

**Issue by mcpasin** [dgrtwo/StackLite#1]
Hi David, after loading required libraries, downloaded the  archive and unzipped it in my working directory, I am not able to open it properly in R.

questions <- read_csv("questions.csv.gz")
I get this message:
Parsed with column specification:
cols(
  `version https://git-lfs.github.com/spec/v1` = col_character()
)

The object "questions" is created and appears in my workspace, though it contains just 2 obs of 1 variable. Am I missing something? Thank you very much!

**Comment by NickLarsen** [comment]
What version of R and the readr package are you using?

**Comment by dgrtwo** [comment]
This was my fault: I had an issue with GitHub LFS (large file service) that stopped it from downloading the full file. It should work now- please try again!

**Comment by mcpasin** [comment]
It now works fine. Thank you!!

**Comment by raghavbali** [comment]
Hi David,
It seems the latest commit has reintroduced the issue. I am getting object in my workspace similar to what @mcpasin mentioned above.

Could you please check it?

Screenshot of issue 
![image](https://cloud.githubusercontent.com/assets/3089481/22828740/00b01204-efc5-11e6-87dc-496472dd690a.png)

Thanks and Regards
