### ISSUE TITLE
Possible data corruption

### ISSUE THREAD

**Issue by sajidrahman** [dgrtwo/StackLite#3]
Hi @dgrtwo ,

While playing with latest StackLite Dataset, I've noticed that **the no. of tags per year calculated from this dataset is quite high than the query result** I've got after running the following query in http://data.stackexchange.com/stackoverflow/

SELECT 
COUNT(p.Id) as QuestionCounts
 from posts p 
 inner join posttags pt on pt.postid = p.id 
 inner join tags t on pt.tagid = t.id 
WHERE p.PostTypeId = 1 AND 
 YEAR(p.CreationDate) = 2009
 AND t.tagname in ('javascript')
GROUP BY PostTypeId

I've played with different tags and years but received the same difference between StackLite dataset and results from SEDE. Here's a screenshot of my little experiment:
![snip20170418_1](https://cloud.githubusercontent.com/assets/4258481/25147346/d5ea7a08-243c-11e7-8495-e3369398264c.png)

I've also run the same experiment with early release (October, 2016) version of StackLite and got the same results. Could you verify it, please @dgrtwo ?

Thanks!

**Comment by dgrtwo** [comment]
StackLite includes deleted questions, SEDE's PostTags does not. This is so users can do analyses of (for example) which tags are more likely to get deleted, or get deleted faster, or do analyses of quality over time that don't get biased by old questions being more likely to be deleted.

You can remove deleted posts by joining with `questions.csv`, which has a DeletionDate column.

Hope that helps!

**Comment by sajidrahman** [comment]
Hi @dgrtwo,
Thank you so much for the prompt response, I really appreciate that! I'm getting more accurate numbers (close to SEDE) now, but still some difference. For example, while calculating no. of posts tagged with **'.net'** until 2017, **SEDE returns 2,43,666 while StackLite returns 2,43,840**. This happens for other tags as well. Could you suggest me if I need to add other filters like DeletionDate in my data processing? Thanks again!
